<?php $quick_links[] = ['link_title' => "Client feedback", 'link_anchor' => 'feedback'];	 ?>
<a name="feedback" id="feedback"></a>
<section id="feedback-section" class="pg-section col-<?php echo (!empty($color)) ? $color : 'red'; ?>">
	<div class="container feedback-quote">
		<div class="row">
			<div class="col-xs-2 text-left">
				<i class="fa fa-quote-left quote-icon"></i>
			</div>
			<div class="col-xs-8">
				<blockquote class="no-border text-center">TLW kept me informed of the progress of our investigation and it has helped us keep our cases up to date.</blockquote>
				<span class="quote-name">Mr P Gaffney, Essex</span>
			</div>
			<div class="col-xs-2 text-right">
				<i class="fa fa-quote-right quote-icon"></i>
			</div>
		</div>
	</div>
	<div class="overlay"></div>
</section>