<?php 
$section_title = "TLW Toolkit";	
//echo '<pre class="debug">';print_r($slides);echo '</pre>';
$quick_links[] = ['link_title' => $section_title, 'link_anchor' => 'toolkit-links'];	
?>

<section id="toolkit-section" class="pg-section with-icon-logo bg-col-<?php echo (!empty($color)) ? $color : 'red'; ?>">
	<a name="toolkit-links" id="toolkit-links" class="section-target"></a>
	
	<div class="container">
					
	</div>
	
	<div class="overlay"></div>
</section>