<a name="toolkit-slides" id="toolkit-slides"></a>
<section class="toolkit-slider">
	<ul class="list-unstyled tk-slider-nav">
		<li class="link-purple active"><a href="#tk-slide-1" title="Specialist healthcare training"><i class="fa fa-stethoscope tk-sn-nav-icon"></i><span class="sr-only">Specialist healthcare training</span></a></li>
		<li class="link-green"><a href="#tk-slide-2" title="Care navigators"><i class="fa fa-life-ring tk-sn-nav-icon"></i><span class="sr-only">Care navigators</span></a></li>
		<li class="link-pink"><a href="#tk-slide-3" title="Legal Services with a clinical edge"><i class="fa fa-balance-scale tk-sn-nav-icon"></i><span class="sr-only">Legal Services with a clinical edge</span></a></li>
		<li class="link-orange"><a href="#tk-slide-4" title="Accredited Legal Expert"><i class="fa fa-thumbs-up tk-sn-nav-icon"></i><span class="sr-only">Accredited Legal Expert</span></a></li>
		<li class="link-blue"><a href="#tk-slide-5" title="Local Care network"><i class="fa fa-code-fork tk-sn-nav-icon"></i><span class="sr-only">Local Care network</span></a></li>
	</ul>
	<div class="tk-slides-outer">
		<div class="tk-slides-inner tk-slide-1-active">
			<article id="tk-slide-1" class="tk-slide slide-purple tk-slide-active">
				<h2 class="slide-banner-header text-center bg-col-purple caps font-slab-serif">Specialist healthcare training</h2>
				<div class="container">
					<div class="row">
						<div class="col-xs-8">
							<div class="scrollable-txt">
								<h3 class="txt-col-purple-dk font-slab-serif bold">TLW teams up with rehab provider to help train staff</h3>
								<p class="bold txt-col-gray">TLW’s serious injury team had training programs from the Northumberland Head Injury Team, Headway, The Spinal Injury Association and private care providers to help understand the longer-term implications and needs of our clients.</p>
	<p>We believe that a fuller understanding of clients’ specific needs will allow our team to provide a more “person-centred” service.</p>
	<p>Serious injuries is a specialist legal area so we provide additional training for the team, as we believe that compensation is only one part of the story.</p>
	<p>Solicitors often tackle individual cases from a legal viewpoint so with specific training in rehabilitation, our team have more of an understanding of longer term implications from a care and rehabilitation perspective following an accident or injury.</p> 
	<p>Often it is not only the individual who suffers, but also the families struggling to find the right rehabilitation, medical care and support for their loved one. Understanding the issues facing our clients mean we understand the impact this has on them and their families.</p>
							</div>
						</div>
						<div class="col-xs-4">
							<figure class="tk-slide-img" style="background-image: url('http://tlwsolicitors.dev/wp-content/uploads/2016/04/Medical-law_v3-380x470-1460465861.jpg')"></figure>
							<div class="overlay"></div>
						</div>
					</div>
				</div>
			</article>
			<article id="tk-slide-2" class="tk-slide slide-green">
				<h2 class="slide-banner-header text-center bg-col-green caps font-slab-serif">Care navigators</h2>
				<div class="container">
					<div class="row">
						<div class="col-xs-8">
							<div class="scrollable-txt">
								<h3 class="txt-col-green-dk font-slab-serif bold">Serious injury effects the injured individual and their family</h3>
								<p class="bold txt-col-gray">The ripple effect of a traumatic injury in terms of emotions that families go through can be serious and long term, our care navigators are there to help deal with this.</p> 
<p>Our specialist care navigators assist our clients and their families to understand some of the many different choices and challenges that will present themselves following a serious injury.</p> 
<p>No one can be expected to be prepared for a life changing event such as a serious traumatic injury, we can however introduce you to one of our expert care navigators who have a great deal of expertise for you to can draw on.</p>
<p>Our navigators have either specialist clinical experience or they have direct personal/family experience of traumatic injury. Our clinical care navigators can provide support to understand treatment, care and rehabilitation options.</p> 
<p>Our care navigators with direct experience of traumatic injury can provide support to families and individuals to help them deal with the challenges arising from the injury.</p>
<p>Care navigators will help with logical recommendations and include the family in the process.</p>
							</div>
						</div>
						<div class="col-xs-4">
							<figure class="tk-slide-img" style="background-image: url('http://tlwsolicitors.dev/wp-content/uploads/2016/04/Top-5-Healthcare-1-380x470-1460466697.jpg?b0027')"></figure>
							<div class="overlay"></div>
						</div>
					</div>
				</div>
			</article>
			<article id="tk-slide-3" class="tk-slide slide-pink">
				<h2 class="slide-banner-header text-center bg-col-pink caps font-slab-serif">Legal Services with a clinical edge</h2>
				<div class="container">
					<div class="row">
						<div class="col-xs-8">
							<div class="scrollable-txt">
								<h3 class="txt-col-pink-dk font-slab-serif bold">We strive to give our clients the best legal services and outcomes from their claim</h3>
								<p class="bold txt-col-gray">As well as using our knowledge and experience to ensure they get the right care, rehabilitation and support to make the best possible recovery from their injury. 
</p>
	<p>TLW believe that getting a client financial compensation for their injury is only part of our job, we also ensure that our clients access the best care, rehabilitation and support available. </p>
							</div>
						</div>
						<div class="col-xs-4">
							<figure class="tk-slide-img" style="background-image: url('http://tlwsolicitors.dev/wp-content/uploads/2016/04/legal-services-380x470-1460467837.jpg?ad3a9')"></figure>
							<div class="overlay"></div>
						</div>
					</div>
				</div>
			</article>
			<article id="tk-slide-4" class="tk-slide slide-orange">
				<h2 class="slide-banner-header text-center bg-col-orange caps font-slab-serif">Accredited Legal Expert</h2>
				<div class="container">
					<div class="row">
						<div class="col-xs-8">
							<div class="scrollable-txt">
								<h3 class="txt-col-orange-dk font-slab-serif bold">Approved and recognised</h3>
								<p class="bold txt-col-gray">TLW are proud to be on the Headway (the brain injury association) list of approved brain injury solicitor's.</p>
	<p>Being in Headway’s approved solicitor directory recognises that we agree to work within the charity’s code of conduct. It also means that Headway have recognised we have the knowledge and experience to provide legal services to individuals who have an acquired brain injury.</p>
<p class="caps bold txt-col-orange">Although there may be many legal firms out there, Headway’s directory is there to filter out those that don’t have the specialist brain or head injury experience.</p>
<p>Given that we have over 15 years’ experience in the personal injury sector we understand that no two people, nor two cases are the same. Choosing a firm on the list isn’t a guarantee that of success, but it does mean the firm has the experience and expertise that Headway require to deal with brain injury cases.</p>
<p>TLW are also accredited by Lexcel is developed specifically for the legal profession and is an optional, recognised accreditation scheme for law firms and in-house legal departments, giving assurance that a practice meets high client care and business management standards.</p>
<p>To gain and retain Lexcel accreditation, the practice must undergo a rigorous initial then annual application and assessment process that includes conducting background checks and an on-site visit from an experienced, trained Lexcel assessor.</p>
							</div>
						</div>
						<div class="col-xs-4">
							<figure class="tk-slide-img" style="background-image: url('http://tlwsolicitors.dev/wp-content/uploads/2016/04/accredited-expert-380x470-1460467625.jpg?2e5bb')"></figure>
							<div class="overlay"></div>
						</div>
					</div>
				</div>
			</article>
			<article id="tk-slide-5" class="tk-slide slide-blue">
				<h2 class="slide-banner-header text-center bg-col-blue caps font-slab-serif">Local Care network</h2>
				<div class="container">
					<div class="row">
						<div class="col-xs-8">
							<div class="scrollable-txt">
								<h3 class="txt-col-blue-dk font-slab-serif bold">TLW teams up with rehab provider to help train staff</h3>
								<p class="bold txt-col-gray">TLW’s serious injury team had training programs from the Northumberland Head Injury Team, Headway, The Spinal Injury Association and private care providers to help understand the longer-term implications and needs of our clients.</p>
	<p>We believe that a fuller understanding of clients’ specific needs will allow our team to provide a more “person-centred” service.</p>
	<p>Serious injuries is a specialist legal area so we provide additional training for the team, as we believe that compensation is only one part of the story.</p>
	<p>Solicitors often tackle individual cases from a legal viewpoint so with specific training in rehabilitation, our team have more of an understanding of longer term implications from a care and rehabilitation perspective following an accident or injury.</p> 
	<p>Often it is not only the individual who suffers, but also the families struggling to find the right rehabilitation, medical care and support for their loved one. Understanding the issues facing our clients mean we understand the impact this has on them and their families.</p>
							</div>
						</div>
						<div class="col-xs-4">
							<figure class="tk-slide-img" style="background-image: url('http://tlwsolicitors.dev/wp-content/uploads/2016/04/care-network-380x470-1460467740.jpg?e4d6d')"></figure>
							<div class="overlay"></div>
						</div>
					</div>
				</div>
			</article>
		</div>
	</div>
</section>
